//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_DistributorEntities : DbContext
    {
        public E_DistributorEntities()
            : base("name=E_DistributorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accountant> Accountants { get; set; }
        public virtual DbSet<IncludeImportedItem> IncludeImportedItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<WarehouseReceipt> WarehouseReceipts { get; set; }
        public virtual DbSet<WarehouseStaff> WarehouseStaffs { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
    }
}
