//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncludeImportedItem
    {
        public int Quantity { get; set; }
        public int TotalPrice { get; set; }
        public int WarehouseReceiptId { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual WarehouseReceipt WarehouseReceipt { get; set; }
    }
}
